# Generated by Django 4.0.3 on 2022-04-10 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchId', models.IntegerField(primary_key=True, serialize=False)),
                ('batchName', models.CharField(max_length=50)),
                ('batchdescription', models.CharField(max_length=50)),
                ('batchStartDate', models.DateField()),
                ('batchEndDate', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Batch',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('courseId', models.IntegerField(primary_key=True, serialize=False)),
                ('courseName', models.CharField(max_length=50)),
                ('courseDescription', models.TextField()),
                ('active', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Course',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('studentCourseId', models.IntegerField(primary_key=True, serialize=False)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.course')),
            ],
            options={
                'verbose_name_plural': 'StudentCourse',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialTitle', models.CharField(max_length=50, null=True)),
                ('materialDescription', models.TextField(null=True)),
                ('active', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('materialURL', models.URLField(null=True)),
                ('batchId', models.ManyToManyField(to='campus.batch')),
                ('courseId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.course')),
            ],
            options={
                'verbose_name_plural': 'Material',
            },
        ),
        migrations.CreateModel(
            name='BatchTime',
            fields=[
                ('batchTimeId', models.IntegerField(primary_key=True, serialize=False)),
                ('batchDay', models.DateField()),
                ('BatchTime', models.TimeField()),
                ('BatchDuration', models.DurationField()),
                ('batchId', models.ManyToManyField(to='campus.batch')),
            ],
            options={
                'verbose_name_plural': 'BatchTime',
            },
        ),
        migrations.CreateModel(
            name='BatchDetail',
            fields=[
                ('batch_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('batchId', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.batch')),
            ],
            options={
                'verbose_name_plural': 'BatchDetails',
            },
        ),
        migrations.AddField(
            model_name='batch',
            name='courseId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.course'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendanceId', models.IntegerField(primary_key=True, serialize=False)),
                ('batchId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='campus.batch')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
    ]
